package PayHostTests;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;
import PayHost.Mockups;
import PayHost.MyObject;
import PayHost.PayHost;
import PayHost.SinglePayment;
import static PayHost.Utilities.prettyFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author App Inlet (Pty) Ltd
 */
public class CardPaymentTest extends javax.swing.JFrame {

    private String requestBody;
    private final String bigTitle = "CardPaymentTest";
    private final String title = "";

    /**
     * Creates new form SinglePayoutTest
     */
    public CardPaymentTest() {
        initComponents();
        bigTitleLabel.setText(bigTitle);
        titleLabel.setText(title);
        reset();
        //loader.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bigTitleLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        payGateIDField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        firstnameField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        responseArea = new javax.swing.JTextArea();
        defaultButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lastnameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        notifyUrlField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        returnUrlField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        merchantOrderIDField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        currencyField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        titleField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cvvField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        cardNumberField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cardExpiryDateField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        budgetPeriodField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        telephoneField = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        mobileField = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        transactionDateField = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setTitle("Test");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setSize(new java.awt.Dimension(1300, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bigTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bigTitleLabel.setForeground(new java.awt.Color(0, 51, 153));
        bigTitleLabel.setText("SingleFollowUp");
        getContentPane().add(bigTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, -1, 20));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 51, 153));
        titleLabel.setText("Query");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 0));

        payGateIDField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        payGateIDField.setForeground(new java.awt.Color(0, 0, 153));
        payGateIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payGateIDFieldActionPerformed(evt);
            }
        });
        payGateIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                payGateIDFieldKeyTyped(evt);
            }
        });
        getContentPane().add(payGateIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 220, 25));

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(0, 0, 153));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordFieldKeyTyped(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 25));

        firstnameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        firstnameField.setForeground(new java.awt.Color(0, 0, 153));
        firstnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstnameFieldActionPerformed(evt);
            }
        });
        firstnameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                firstnameFieldKeyTyped(evt);
            }
        });
        getContentPane().add(firstnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, 25));

        sendButton.setBackground(new java.awt.Color(0, 0, 204));
        sendButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setText("Send");
        sendButton.setToolTipText("Sample");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 310, 40));

        requestArea.setColumns(20);
        requestArea.setRows(5);
        requestArea.setToolTipText("[750, 510]");
        requestArea.setName("Test"); // NOI18N
        jScrollPane1.setViewportView(requestArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 660, 220));

        responseArea.setColumns(20);
        responseArea.setRows(5);
        jScrollPane2.setViewportView(responseArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, 660, 230));

        defaultButton.setBackground(new java.awt.Color(0, 0, 255));
        defaultButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        defaultButton.setForeground(new java.awt.Color(255, 255, 255));
        defaultButton.setText("Default");
        defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(defaultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 340, 40));

        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel5.setText("Firstname");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        lastnameField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lastnameField.setForeground(new java.awt.Color(0, 0, 153));
        lastnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameFieldActionPerformed(evt);
            }
        });
        lastnameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lastnameFieldKeyTyped(evt);
            }
        });
        getContentPane().add(lastnameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 220, 25));

        jLabel6.setText("Lastname");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        emailField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(0, 0, 153));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailFieldKeyTyped(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 220, 25));

        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        notifyUrlField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        notifyUrlField.setForeground(new java.awt.Color(0, 0, 153));
        notifyUrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyUrlFieldActionPerformed(evt);
            }
        });
        notifyUrlField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                notifyUrlFieldKeyTyped(evt);
            }
        });
        getContentPane().add(notifyUrlField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 220, 25));

        jLabel8.setText("Notify Url");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        returnUrlField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        returnUrlField.setForeground(new java.awt.Color(0, 0, 153));
        returnUrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnUrlFieldActionPerformed(evt);
            }
        });
        returnUrlField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                returnUrlFieldKeyTyped(evt);
            }
        });
        getContentPane().add(returnUrlField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 220, 25));

        jLabel9.setText("Return Url");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        merchantOrderIDField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        merchantOrderIDField.setForeground(new java.awt.Color(0, 0, 153));
        merchantOrderIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                merchantOrderIDFieldActionPerformed(evt);
            }
        });
        merchantOrderIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                merchantOrderIDFieldKeyTyped(evt);
            }
        });
        getContentPane().add(merchantOrderIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 220, 25));

        jLabel10.setText("Merchant Order Id");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        currencyField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        currencyField.setForeground(new java.awt.Color(0, 0, 153));
        currencyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyFieldActionPerformed(evt);
            }
        });
        currencyField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currencyFieldKeyTyped(evt);
            }
        });
        getContentPane().add(currencyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 220, 25));

        jLabel11.setText("Currency");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        amountField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amountField.setForeground(new java.awt.Color(0, 0, 153));
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        amountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountFieldKeyTyped(evt);
            }
        });
        getContentPane().add(amountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 220, 25));

        jLabel12.setText("Amount");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        titleField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        titleField.setForeground(new java.awt.Color(0, 0, 153));
        titleField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titleFieldActionPerformed(evt);
            }
        });
        titleField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                titleFieldKeyTyped(evt);
            }
        });
        getContentPane().add(titleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 25));

        jLabel13.setText("Title");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        cvvField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cvvField.setForeground(new java.awt.Color(0, 0, 153));
        cvvField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cvvFieldActionPerformed(evt);
            }
        });
        cvvField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cvvFieldKeyTyped(evt);
            }
        });
        getContentPane().add(cvvField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 220, 25));

        jLabel14.setText("CVV");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        jLabel15.setText("Pay Gate ID");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, -1));

        cardNumberField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cardNumberField.setForeground(new java.awt.Color(0, 0, 153));
        cardNumberField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberFieldActionPerformed(evt);
            }
        });
        cardNumberField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardNumberFieldKeyTyped(evt);
            }
        });
        getContentPane().add(cardNumberField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 220, 25));

        jLabel27.setText("Card Number");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, -1, -1));

        cardExpiryDateField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cardExpiryDateField.setForeground(new java.awt.Color(0, 0, 153));
        cardExpiryDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardExpiryDateFieldActionPerformed(evt);
            }
        });
        cardExpiryDateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cardExpiryDateFieldKeyTyped(evt);
            }
        });
        getContentPane().add(cardExpiryDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 220, 25));

        jLabel28.setText("Card Expiry Date");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, -1));

        budgetPeriodField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        budgetPeriodField.setForeground(new java.awt.Color(0, 0, 153));
        budgetPeriodField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                budgetPeriodFieldActionPerformed(evt);
            }
        });
        budgetPeriodField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                budgetPeriodFieldKeyTyped(evt);
            }
        });
        getContentPane().add(budgetPeriodField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 620, 220, 25));

        jLabel29.setText("Budget Period ");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 600, -1, -1));

        telephoneField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        telephoneField.setForeground(new java.awt.Color(0, 0, 153));
        telephoneField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneFieldActionPerformed(evt);
            }
        });
        telephoneField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                telephoneFieldKeyTyped(evt);
            }
        });
        getContentPane().add(telephoneField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 220, 25));

        jLabel30.setText("Telephone");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, -1, -1));

        mobileField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        mobileField.setForeground(new java.awt.Color(0, 0, 153));
        mobileField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileFieldActionPerformed(evt);
            }
        });
        mobileField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mobileFieldKeyTyped(evt);
            }
        });
        getContentPane().add(mobileField, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 220, 25));

        jLabel31.setText("Mobile");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        transactionDateField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        transactionDateField.setForeground(new java.awt.Color(0, 0, 153));
        transactionDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionDateFieldActionPerformed(evt);
            }
        });
        transactionDateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                transactionDateFieldKeyTyped(evt);
            }
        });
        getContentPane().add(transactionDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 220, 25));

        jLabel32.setText("Transaction Date");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 20, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void payGateIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payGateIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payGateIDFieldActionPerformed

    private void payGateIDFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payGateIDFieldKeyTyped
        display();
    }//GEN-LAST:event_payGateIDFieldKeyTyped

    private void passwordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_passwordFieldKeyTyped

    private void firstnameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_firstnameFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_firstnameFieldKeyTyped

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_defaultButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        try {
            PayHost ph = new PayHost("https://secure.paygate.co.za/payhost/process.trans", "ns1");
            SinglePayment sp = new SinglePayment(ph);
            MyObject params = new MyObject();
            params.setProperty("payGateID", payGateIDField.getText());
            params.setProperty("password", passwordField.getText());
            params.setProperty("title", titleField.getText());
            params.setProperty("firstname", firstnameField.getText());
            params.setProperty("lastname", lastnameField.getText());
            params.setProperty("email", emailField.getText());
            params.setProperty("notifyUrl", notifyUrlField.getText());
            params.setProperty("returnUrl", returnUrlField.getText());
            params.setProperty("merchantOrderID", merchantOrderIDField.getText());
            params.setProperty("currency", currencyField.getText());
            params.setProperty("amount", amountField.getText());
            params.setProperty("cvv", cvvField.getText());
            params.setProperty("cardNumber", cardNumberField.getText());
            params.setProperty("cardExpiryDate", cardExpiryDateField.getText());
            params.setProperty("budgetPeriod", budgetPeriodField.getText());
            params.setProperty("telephone", telephoneField.getText());
            params.setProperty("mobile", mobileField.getText());
            String res = sp.cardPayment(params);
            responseArea.setText(prettyFormat(res));
            /*MyObject status = sp.getUtil().getStatus(res);
            if (sp.error(res)) {
                // Request is denied
                System.out.println("Error : " + status.getProperty("ResultDescription"));
            } else {
                // Request is applied
                System.out.println("No Error");
            }*/
        } catch (IOException | ParserConfigurationException | SAXException ex) {
            Logger.getLogger(CardPaymentTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void lastnameFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lastnameFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_lastnameFieldKeyTyped

    private void lastnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameFieldActionPerformed

    private void firstnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstnameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void emailFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_emailFieldKeyTyped

    private void notifyUrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyUrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notifyUrlFieldActionPerformed

    private void notifyUrlFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_notifyUrlFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_notifyUrlFieldKeyTyped

    private void returnUrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnUrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnUrlFieldActionPerformed

    private void returnUrlFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_returnUrlFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_returnUrlFieldKeyTyped

    private void merchantOrderIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_merchantOrderIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_merchantOrderIDFieldActionPerformed

    private void merchantOrderIDFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_merchantOrderIDFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_merchantOrderIDFieldKeyTyped

    private void currencyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currencyFieldActionPerformed

    private void currencyFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currencyFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_currencyFieldKeyTyped

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void amountFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_amountFieldKeyTyped

    private void titleFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titleFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titleFieldActionPerformed

    private void titleFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_titleFieldKeyTyped

    private void cvvFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cvvFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cvvFieldActionPerformed

    private void cvvFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cvvFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_cvvFieldKeyTyped

    private void cardNumberFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberFieldActionPerformed

    private void cardNumberFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardNumberFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cardNumberFieldKeyTyped

    private void cardExpiryDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardExpiryDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardExpiryDateFieldActionPerformed

    private void cardExpiryDateFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cardExpiryDateFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_cardExpiryDateFieldKeyTyped

    private void budgetPeriodFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_budgetPeriodFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_budgetPeriodFieldActionPerformed

    private void budgetPeriodFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_budgetPeriodFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_budgetPeriodFieldKeyTyped

    private void telephoneFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneFieldActionPerformed

    private void telephoneFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneFieldKeyTyped

    private void mobileFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileFieldActionPerformed

    private void mobileFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileFieldKeyTyped

    private void transactionDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionDateFieldActionPerformed

    private void transactionDateFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transactionDateFieldKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionDateFieldKeyTyped

    /**
     * display params in text area
     */
    private void display() {
        // TODO add your handling code here:
        String body = "<ns1:SinglePaymentRequest>\n"
                + "	<ns1:CardPaymentRequest>\n"
                + "		<ns1:Account>\n"
                + "			<ns1:PayGateId>" + payGateIDField.getText() + "</ns1:PayGateId>\n"
                + "			<ns1:Password>" + passwordField.getText() + "</ns1:Password>\n"
                + "		</ns1:Account>\n"
                + "		<ns1:Customer>\n"
                + "			<ns1:Title>" + titleField.getText() + "</ns1:Title>\n"
                + "			<ns1:FirstName>" + firstnameField.getText() + "</ns1:FirstName>\n"
                + "			<ns1:LastName>" + lastnameField.getText() + "</ns1:LastName>\n"
                + "			<ns1:Email>" + emailField.getText() + "</ns1:Email>\n"
                + "		</ns1:Customer>\n"
                + "		<ns1:CardNumber>" + cardNumberField.getText() + "</ns1:CardNumber>\n"
                + "		<ns1:CardExpiryDate>" + cardExpiryDateField.getText() + "</ns1:CardExpiryDate>\n"
                + "		<ns1:CVV>" + cvvField.getText() + "</ns1:CVV>\n"
                + "		<ns1:BudgetPeriod>" + budgetPeriodField.getText() + "</ns1:BudgetPeriod>\n"
                + "		<ns1:Redirect>\n"
                + "			<ns1:NotifyUrl>" + notifyUrlField.getText() + "</ns1:NotifyUrl>\n"
                + "			<ns1:ReturnUrl>" + returnUrlField.getText() + "</ns1:ReturnUrl>\n"
                + "		</ns1:Redirect>\n"
                + "		<ns1:Order>\n"
                + "			<ns1:MerchantOrderId>" + merchantOrderIDField.getText() + "</ns1:MerchantOrderId>\n"
                + "			<ns1:Currency>" + currencyField.getText() + "</ns1:Currency>\n"
                + "			<ns1:Amount>" + amountField.getText() + "</ns1:Amount>\n"
                + "			<ns1:TransactionDate>" + transactionDateField.getText() + "</ns1:TransactionDate>\n"
                + "		</ns1:Order>\n"
                + "	</ns1:CardPaymentRequest>\n"
                + "</ns1:SinglePaymentRequest>\n";
        requestArea.setText(body);
        //requestArea.setText(prettyFormat(body));
    }

    /**
     * default params in text area
     */
    private void reset() {
        // TODO add your handling code here:
        MyObject m = new Mockups().singlePaymentCardSimple();

        String body = "<ns1:SinglePaymentRequest>\n"
                + "	<ns1:CardPaymentRequest>\n"
                + "		<ns1:Account>\n"
                + "			<ns1:PayGateId>" + m.getProperty("payGateID") + "</ns1:PayGateId>\n"
                + "			<ns1:Password>" + m.getProperty("password") + "</ns1:Password>\n"
                + "		</ns1:Account>\n"
                + "		<ns1:Customer>\n"
                + "			<ns1:Title>" + m.getProperty("title") + "</ns1:Title>\n"
                + "			<ns1:FirstName>" + m.getProperty("firstname") + "</ns1:FirstName>\n"
                + "			<ns1:LastName>" + m.getProperty("lastname") + "</ns1:LastName>\n"
                + "			<ns1:Email>" + m.getProperty("email") + "</ns1:Email>\n"
                + "		</ns1:Customer>\n"
                + "		<ns1:CardNumber>" + m.getProperty("cardNumber") + "</ns1:CardNumber>\n"
                + "		<ns1:CardExpiryDate>" + m.getProperty("cardExpiryDate") + "</ns1:CardExpiryDate>\n"
                + "		<ns1:CVV>" + m.getProperty("cvv") + "</ns1:CVV>\n"
                + "		<ns1:BudgetPeriod>" + m.getProperty("budgetPeriod") + "</ns1:BudgetPeriod>\n"
                + "		<ns1:Redirect>\n"
                + "			<ns1:NotifyUrl>" + m.getProperty("notifyUrl") + "</ns1:NotifyUrl>\n"
                + "			<ns1:ReturnUrl>" + m.getProperty("returnUrl") + "</ns1:ReturnUrl>\n"
                + "		</ns1:Redirect>\n"
                + "		<ns1:Order>\n"
                + "			<ns1:MerchantOrderId>" + m.getProperty("merchantOrderID") + "</ns1:MerchantOrderId>\n"
                + "			<ns1:Currency>" + m.getProperty("currency") + "</ns1:Currency>\n"
                + "			<ns1:Amount>" + m.getProperty("amount") + "</ns1:Amount>\n"
                + "			<ns1:TransactionDate>" + m.getProperty("transactionDate") + "</ns1:TransactionDate>\n"
                + "		</ns1:Order>\n"
                + "	</ns1:CardPaymentRequest>\n"
                + "</ns1:SinglePaymentRequest>\n";
        payGateIDField.setText((String) m.getProperty("payGateID"));
        passwordField.setText((String) m.getProperty("password"));
        titleField.setText((String) m.getProperty("title"));
        firstnameField.setText((String) m.getProperty("firstname"));
        lastnameField.setText((String) m.getProperty("lastname"));
        emailField.setText((String) m.getProperty("email"));
        notifyUrlField.setText((String) m.getProperty("notifyUrl"));
        returnUrlField.setText((String) m.getProperty("returnUrl"));
        merchantOrderIDField.setText((String) m.getProperty("merchantOrderID"));
        currencyField.setText((String) m.getProperty("currency"));
        amountField.setText((String) m.getProperty("amount"));
        cardNumberField.setText((String) m.getProperty("cardNumber"));
        cardExpiryDateField.setText((String) m.getProperty("cardExpiryDate"));
        cvvField.setText((String) m.getProperty("cvv"));
        budgetPeriodField.setText((String) m.getProperty("budgetPeriod"));
        mobileField.setText((String) m.getProperty("mobile"));
        telephoneField.setText((String) m.getProperty("telephone"));
        transactionDateField.setText((String) m.getProperty("transactionDate"));
        requestArea.setText(body);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinglePayoutTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new CardPaymentTest().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel bigTitleLabel;
    private javax.swing.JTextField budgetPeriodField;
    private javax.swing.JTextField cardExpiryDateField;
    private javax.swing.JTextField cardNumberField;
    private javax.swing.JTextField currencyField;
    private javax.swing.JTextField cvvField;
    private javax.swing.JButton defaultButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField firstnameField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JTextField merchantOrderIDField;
    private javax.swing.JTextField mobileField;
    private javax.swing.JTextField notifyUrlField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField payGateIDField;
    private javax.swing.JTextArea requestArea;
    private javax.swing.JTextArea responseArea;
    private javax.swing.JTextField returnUrlField;
    private javax.swing.JButton sendButton;
    private javax.swing.JTextField telephoneField;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField transactionDateField;
    // End of variables declaration//GEN-END:variables
}
