package PayHostTests;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;
import PayHost.Mockups;
import PayHost.MyObject;
import PayHost.PayHost;
import PayHost.SinglePayment;
import PayHost.SingleVault;
import static PayHost.Utilities.prettyFormat;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author App Inlet (Pty) Ltd
 */
public class TokenPaymentTest extends javax.swing.JFrame {

    private String requestBody;
    private final String bigTitle = "TokenPayment";
    private final String title = "";

    /**
     * Creates new form SinglePayoutTest
     */
    public TokenPaymentTest() {
        initComponents();
        bigTitleLabel.setText(bigTitle);
        titleLabel.setText(title);
        reset();
        //loader.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bigTitleLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        payGateIDField = new javax.swing.JTextField();
        passwordField = new javax.swing.JTextField();
        notifyUrlField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        responseArea = new javax.swing.JTextArea();
        defaultButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tokenField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tokenDetailField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        currencyField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setTitle("Test");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setSize(new java.awt.Dimension(1100, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bigTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bigTitleLabel.setForeground(new java.awt.Color(0, 51, 153));
        bigTitleLabel.setText("SingleFollowUp");
        getContentPane().add(bigTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 51, 153));
        titleLabel.setText("Query");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, 0));

        payGateIDField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        payGateIDField.setForeground(new java.awt.Color(0, 0, 153));
        payGateIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payGateIDFieldActionPerformed(evt);
            }
        });
        payGateIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                payGateIDFieldKeyTyped(evt);
            }
        });
        getContentPane().add(payGateIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 280, 25));

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        passwordField.setForeground(new java.awt.Color(0, 0, 153));
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordFieldKeyTyped(evt);
            }
        });
        getContentPane().add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 280, 25));

        notifyUrlField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        notifyUrlField.setForeground(new java.awt.Color(0, 0, 153));
        notifyUrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyUrlFieldActionPerformed(evt);
            }
        });
        notifyUrlField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                notifyUrlFieldKeyTyped(evt);
            }
        });
        getContentPane().add(notifyUrlField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 280, 25));

        sendButton.setBackground(new java.awt.Color(0, 0, 204));
        sendButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setText("Send");
        sendButton.setToolTipText("Sample");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 500, 330, 40));

        requestArea.setColumns(20);
        requestArea.setRows(5);
        requestArea.setToolTipText("[750, 510]");
        requestArea.setName("Test"); // NOI18N
        jScrollPane1.setViewportView(requestArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 690, 220));

        responseArea.setColumns(20);
        responseArea.setRows(5);
        jScrollPane2.setViewportView(responseArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 260, 690, 230));

        defaultButton.setBackground(new java.awt.Color(0, 0, 255));
        defaultButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        defaultButton.setForeground(new java.awt.Color(255, 255, 255));
        defaultButton.setText("Default");
        defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(defaultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 500, 350, 40));

        jLabel3.setText("Pay Gate ID");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, -1));

        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel5.setText("Token");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        tokenField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tokenField.setForeground(new java.awt.Color(0, 0, 153));
        tokenField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokenFieldActionPerformed(evt);
            }
        });
        tokenField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tokenFieldKeyTyped(evt);
            }
        });
        getContentPane().add(tokenField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 280, 25));

        jLabel6.setText("Token Detail");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        tokenDetailField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tokenDetailField.setForeground(new java.awt.Color(0, 0, 153));
        tokenDetailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tokenDetailFieldActionPerformed(evt);
            }
        });
        tokenDetailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tokenDetailFieldKeyTyped(evt);
            }
        });
        getContentPane().add(tokenDetailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 280, 25));

        jLabel10.setText("Merchant Order Id");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        currencyField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        currencyField.setForeground(new java.awt.Color(0, 0, 153));
        currencyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyFieldActionPerformed(evt);
            }
        });
        currencyField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currencyFieldKeyTyped(evt);
            }
        });
        getContentPane().add(currencyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 280, 25));

        jLabel11.setText("Currency");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        amountField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amountField.setForeground(new java.awt.Color(0, 0, 153));
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        amountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountFieldKeyTyped(evt);
            }
        });
        getContentPane().add(amountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 280, 25));

        jLabel12.setText("Amount");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void payGateIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payGateIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payGateIDFieldActionPerformed

    private void payGateIDFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payGateIDFieldKeyTyped
        display();
    }//GEN-LAST:event_payGateIDFieldKeyTyped

    private void passwordFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_passwordFieldKeyTyped

    private void notifyUrlFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_notifyUrlFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_notifyUrlFieldKeyTyped

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_defaultButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        try {
            PayHost ph = new PayHost("https://secure.paygate.co.za/payhost/process.trans", "ns1");
            SinglePayment sp = new SinglePayment(ph);
            MyObject params = new MyObject();
            params.setProperty("payGateID", payGateIDField.getText());
            params.setProperty("password", passwordField.getText());
            params.setProperty("token", notifyUrlField.getText());
            params.setProperty("tokenDetail", tokenField.getText());
            params.setProperty("merchantOrderID", tokenDetailField.getText());
            params.setProperty("currency", currencyField.getText());
            params.setProperty("amount", amountField.getText());
            String res = sp.tokenPayment(params);
            responseArea.setText(prettyFormat(res));
            /*MyObject status = sp.getUtil().getStatus(res);
            if (sp.error(res)) {
                // Request is denied
                System.out.println("Error : " + status.getProperty("ResultDescription"));
            } else {
                // Request is applied
                Syst*/

        } catch (IOException | ParserConfigurationException | SAXException ex) {
            Logger.getLogger(SinglePayoutTest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void tokenFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tokenFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_tokenFieldKeyTyped

    private void tokenFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokenFieldActionPerformed

    private void notifyUrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyUrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notifyUrlFieldActionPerformed

    private void tokenDetailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tokenDetailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tokenDetailFieldActionPerformed

    private void tokenDetailFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tokenDetailFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_tokenDetailFieldKeyTyped

    private void currencyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currencyFieldActionPerformed

    private void currencyFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currencyFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_currencyFieldKeyTyped

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void amountFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_amountFieldKeyTyped

    /**
     * display params in text area
     */
    private void display() {
        // TODO add your handling code here:
        String body = "<ns1:SinglePayment>\n"
                + "	<ns1:TokenPaymentRequest>\n"
                + "		<ns1:Account>\n"
                + "			<ns1:PayGateId>" + payGateIDField.getText() + "</ns1:PayGateId>\n"
                + "			<ns1:Password>" + passwordField.getText() + "</ns1:Password>\n"
                + "		</ns1:Account>\n"
                + "		<ns1:Token>" + notifyUrlField.getText() + "</ns1:Token>\n"
                + "		<ns1:TokenDetail>" + tokenField.getText() + "</ns1:TokenDetail>\n"
                + "		<ns1:Order>\n"
                + "			<ns1:MerchantOrderId>" + tokenDetailField.getText() + "</ns1:MerchantOrderId>\n"
                + "			<ns1:Currency>" + currencyField.getText() + "</ns1:Currency>\n"
                + "			<ns1:Amount>" + amountField.getText() + "</ns1:Amount>\n"
                + "		</ns1:Order>\n"
                + "	</ns1:TokenPaymentRequest>\n"
                + "</ns1:SinglePayment>\n";
        requestArea.setText(body);
    }

    /**
     * default params in text area
     */
    private void reset() {
        // TODO add your handling code here:
        MyObject m = new Mockups().singlePaymentToken();

        String body = "<ns1:SinglePayment>\n"
                + "	<ns1:TokenPaymentRequest>\n"
                + "		<ns1:Account>\n"
                + "			<ns1:PayGateId>" + m.getProperty("payGateID") + "</ns1:PayGateId>\n"
                + "			<ns1:Password>" + m.getProperty("password") + "</ns1:Password>\n"
                + "		</ns1:Account>\n"
                + "		<ns1:Token>" + m.getProperty("token") + "</ns1:Token>\n"
                + "		<ns1:TokenDetail>" + m.getProperty("tokenDetail") + "</ns1:TokenDetail>\n"
                + "		<ns1:Order>\n"
                + "			<ns1:MerchantOrderId>" + m.getProperty("merchantOrderID") + "</ns1:MerchantOrderId>\n"
                + "			<ns1:Currency>" + m.getProperty("currency") + "</ns1:Currency>\n"
                + "			<ns1:Amount>" + m.getProperty("amount") + "</ns1:Amount>\n"
                + "		</ns1:Order>\n"
                + "	</ns1:TokenPaymentRequest>\n"
                + "</ns1:SinglePayment>\n";
        payGateIDField.setText((String) m.getProperty("payGateID"));
        passwordField.setText((String) m.getProperty("password"));
        notifyUrlField.setText((String) m.getProperty("token"));
        tokenField.setText((String) m.getProperty("tokenDetail"));
        tokenDetailField.setText((String) m.getProperty("merchantOrderID"));
        currencyField.setText((String) m.getProperty("currency"));
        amountField.setText((String) m.getProperty("amount"));
        requestArea.setText(body);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SinglePayoutTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new TokenPaymentTest().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel bigTitleLabel;
    private javax.swing.JTextField currencyField;
    private javax.swing.JButton defaultButton;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField notifyUrlField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField payGateIDField;
    private javax.swing.JTextArea requestArea;
    private javax.swing.JTextArea responseArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField tokenDetailField;
    private javax.swing.JTextField tokenField;
    // End of variables declaration//GEN-END:variables
}
