package PayWebTests;

import PayWeb3.PayWeb;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import PayHost.Mockups;
import PayHost.MyObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author App Inlet (Pty) Ltd
 */
public class Initiate extends javax.swing.JFrame {

    private String requestBody;
    private final String bigTitle = "PayWeb3";
    private final String title = "Initiate";

    /**
     * Creates new form SinglePayoutTest
     */
    public Initiate() {
        initComponents();
        bigTitleLabel.setText(bigTitle);
        titleLabel.setText(title);
        reset();
        //loader.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bigTitleLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        payGateIDField = new javax.swing.JTextField();
        referenceField = new javax.swing.JTextField();
        localeField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        responseArea = new javax.swing.JTextArea();
        defaultButton = new javax.swing.JButton();
        REFERENCE = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        checksumField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        notifyUrlField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        returnUrlField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        currencyField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        transactionDateField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        countryField = new javax.swing.JTextField();

        setTitle("Test");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setSize(new java.awt.Dimension(1300, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bigTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bigTitleLabel.setForeground(new java.awt.Color(0, 51, 153));
        bigTitleLabel.setText("PayWeb3");
        getContentPane().add(bigTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 51, 153));
        titleLabel.setText("Initiate");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 30));

        payGateIDField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        payGateIDField.setForeground(new java.awt.Color(0, 0, 153));
        payGateIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payGateIDFieldActionPerformed(evt);
            }
        });
        payGateIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                payGateIDFieldKeyTyped(evt);
            }
        });
        getContentPane().add(payGateIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 220, 25));

        referenceField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        referenceField.setForeground(new java.awt.Color(0, 0, 153));
        referenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceFieldActionPerformed(evt);
            }
        });
        referenceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                referenceFieldKeyTyped(evt);
            }
        });
        getContentPane().add(referenceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 25));

        localeField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        localeField.setForeground(new java.awt.Color(0, 0, 153));
        localeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                localeFieldActionPerformed(evt);
            }
        });
        localeField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                localeFieldKeyTyped(evt);
            }
        });
        getContentPane().add(localeField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 220, 25));

        sendButton.setBackground(new java.awt.Color(0, 0, 204));
        sendButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setText("Send");
        sendButton.setToolTipText("Sample");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 410, 40));

        requestArea.setColumns(20);
        requestArea.setRows(5);
        requestArea.setToolTipText("[750, 510]");
        requestArea.setName("Test"); // NOI18N
        jScrollPane1.setViewportView(requestArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 860, 220));

        responseArea.setColumns(20);
        responseArea.setRows(5);
        jScrollPane2.setViewportView(responseArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 860, 230));

        defaultButton.setBackground(new java.awt.Color(0, 0, 255));
        defaultButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        defaultButton.setForeground(new java.awt.Color(255, 255, 255));
        defaultButton.setText("Default");
        defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(defaultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 410, 40));

        REFERENCE.setText("Reference");
        getContentPane().add(REFERENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel5.setText("Locale");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        checksumField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checksumField.setForeground(new java.awt.Color(0, 0, 153));
        checksumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checksumFieldActionPerformed(evt);
            }
        });
        checksumField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                checksumFieldKeyTyped(evt);
            }
        });
        getContentPane().add(checksumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 220, 25));

        jLabel6.setText("Checksum");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        emailField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        emailField.setForeground(new java.awt.Color(0, 0, 153));
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        emailField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                emailFieldKeyTyped(evt);
            }
        });
        getContentPane().add(emailField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 220, 25));

        jLabel7.setText("Email");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        notifyUrlField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        notifyUrlField.setForeground(new java.awt.Color(0, 0, 153));
        notifyUrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notifyUrlFieldActionPerformed(evt);
            }
        });
        notifyUrlField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                notifyUrlFieldKeyTyped(evt);
            }
        });
        getContentPane().add(notifyUrlField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 220, 25));

        jLabel8.setText("Notify Url");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        returnUrlField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        returnUrlField.setForeground(new java.awt.Color(0, 0, 153));
        returnUrlField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnUrlFieldActionPerformed(evt);
            }
        });
        returnUrlField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                returnUrlFieldKeyTyped(evt);
            }
        });
        getContentPane().add(returnUrlField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 220, 25));

        jLabel9.setText("Return Url");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, -1, -1));

        currencyField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        currencyField.setForeground(new java.awt.Color(0, 0, 153));
        currencyField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currencyFieldActionPerformed(evt);
            }
        });
        currencyField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                currencyFieldKeyTyped(evt);
            }
        });
        getContentPane().add(currencyField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 220, 25));

        jLabel11.setText("Currency");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        amountField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        amountField.setForeground(new java.awt.Color(0, 0, 153));
        amountField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountFieldActionPerformed(evt);
            }
        });
        amountField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                amountFieldKeyTyped(evt);
            }
        });
        getContentPane().add(amountField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 220, 25));

        jLabel12.setText("Amount");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, -1, -1));

        transactionDateField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        transactionDateField.setForeground(new java.awt.Color(0, 0, 153));
        transactionDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionDateFieldActionPerformed(evt);
            }
        });
        transactionDateField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                transactionDateFieldKeyTyped(evt);
            }
        });
        getContentPane().add(transactionDateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 220, 25));

        jLabel13.setText("Transaction Date");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel15.setText("Pay Gate ID");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 80, -1));

        jLabel24.setText("Country");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 80, -1));

        countryField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        countryField.setForeground(new java.awt.Color(0, 0, 153));
        countryField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryFieldActionPerformed(evt);
            }
        });
        countryField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                countryFieldKeyTyped(evt);
            }
        });
        getContentPane().add(countryField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, 220, 25));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void referenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenceFieldActionPerformed

    private void payGateIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payGateIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payGateIDFieldActionPerformed

    private void payGateIDFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payGateIDFieldKeyTyped
        display();
    }//GEN-LAST:event_payGateIDFieldKeyTyped

    private void referenceFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_referenceFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_referenceFieldKeyTyped

    private void localeFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_localeFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_localeFieldKeyTyped

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_defaultButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        try {
            MyObject object = new MyObject();
            object.setProperty("PAYGATE_ID", payGateIDField.getText());
            object.setProperty("REFERENCE", referenceField.getText());
            object.setProperty("AMOUNT", amountField.getText());
            object.setProperty("CURRENCY", currencyField.getText());
            object.setProperty("RETURN_URL", returnUrlField.getText());
            object.setProperty("TRANSACTION_DATE", transactionDateField.getText());
            object.setProperty("LOCALE", localeField.getText());
            object.setProperty("COUNTRY", countryField.getText());
            object.setProperty("EMAIL", emailField.getText());
            object.setProperty("CHECKSUM", checksumField.getText());
            PayWeb pw = new PayWeb();
            String response = pw.request(pw.body(object));
            responseArea.setText(response);
        } catch (IOException ex) {
            Logger.getLogger(Initiate.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void checksumFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checksumFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_checksumFieldKeyTyped

    private void checksumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checksumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checksumFieldActionPerformed

    private void localeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_localeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_localeFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void emailFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_emailFieldKeyTyped

    private void notifyUrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notifyUrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notifyUrlFieldActionPerformed

    private void notifyUrlFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_notifyUrlFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_notifyUrlFieldKeyTyped

    private void returnUrlFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnUrlFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_returnUrlFieldActionPerformed

    private void returnUrlFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_returnUrlFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_returnUrlFieldKeyTyped

    private void currencyFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currencyFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_currencyFieldActionPerformed

    private void currencyFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_currencyFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_currencyFieldKeyTyped

    private void amountFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountFieldActionPerformed

    private void amountFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_amountFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_amountFieldKeyTyped

    private void transactionDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionDateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transactionDateFieldActionPerformed

    private void transactionDateFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_transactionDateFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_transactionDateFieldKeyTyped

    private void countryFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryFieldActionPerformed

    private void countryFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_countryFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_countryFieldKeyTyped

    /**
     * display params in text area
     */
    private void display() {
        // TODO add your handling code here:
        PayWeb pw = new PayWeb();
        MyObject object = new MyObject();
        object.setProperty("PAYGATE_ID", payGateIDField.getText());
        object.setProperty("REFERENCE", referenceField.getText());
        object.setProperty("AMOUNT", amountField.getText());
        object.setProperty("CURRENCY", currencyField.getText());
        object.setProperty("RETURN_URL", returnUrlField.getText());
        object.setProperty("TRANSACTION_DATE", transactionDateField.getText());
        object.setProperty("LOCALE", localeField.getText());
        object.setProperty("COUNTRY", countryField.getText());
        object.setProperty("EMAIL", emailField.getText());
        object.setProperty("CHECKSUM", checksumField.getText());
        String body = pw.bodyDisplay(object);
        requestArea.setText(body);
    }

    /**
     * default params in text area
     */
    private void reset() {
        // TODO add your handling code here:
        MyObject m = new Mockups().paywebInitiate();
        String body = new PayWeb().bodyDisplay(m);
        payGateIDField.setText((String) m.getProperty("PAYGATE_ID"));
        referenceField.setText((String) m.getProperty("REFERENCE"));
        transactionDateField.setText((String) m.getProperty("TRANSACTION_DATE"));
        localeField.setText((String) m.getProperty("LOCALE"));
        checksumField.setText((String) m.getProperty("CHECKSUM"));
        emailField.setText((String) m.getProperty("EMAIL"));
        notifyUrlField.setText((String) m.getProperty("Notify_URL"));
        returnUrlField.setText((String) m.getProperty("RETURN_URL"));
        currencyField.setText((String) m.getProperty("CURRENCY"));
        amountField.setText((String) m.getProperty("AMOUNT"));
        countryField.setText((String) m.getProperty("COUNTRY"));
        requestArea.setText(body);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Initiate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Initiate().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel REFERENCE;
    private javax.swing.JTextField amountField;
    private javax.swing.JLabel bigTitleLabel;
    private javax.swing.JTextField checksumField;
    private javax.swing.JTextField countryField;
    private javax.swing.JTextField currencyField;
    private javax.swing.JButton defaultButton;
    private javax.swing.JTextField emailField;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField localeField;
    private javax.swing.JTextField notifyUrlField;
    private javax.swing.JTextField payGateIDField;
    private javax.swing.JTextField referenceField;
    private javax.swing.JTextArea requestArea;
    private javax.swing.JTextArea responseArea;
    private javax.swing.JTextField returnUrlField;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField transactionDateField;
    // End of variables declaration//GEN-END:variables
}
