package PayWebTests;

import PayWeb3.PayWeb;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import PayHost.Mockups;
import PayHost.MyObject;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author App Inlet (Pty) Ltd
 */
public class Query extends javax.swing.JFrame {

    private String requestBody;
    private final String bigTitle = "PayWeb3";
    private final String title = "Query";

    /**
     * Creates new form Query
     */
    public Query() {
        initComponents();
        bigTitleLabel.setText(bigTitle);
        titleLabel.setText(title);
        reset();
        //loader.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bigTitleLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        payGateIDField = new javax.swing.JTextField();
        referenceField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        responseArea = new javax.swing.JTextArea();
        defaultButton = new javax.swing.JButton();
        REFERENCE = new javax.swing.JLabel();
        checksumField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        payRequestIDField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setTitle("Test");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1100, 650));
        setSize(new java.awt.Dimension(1300, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bigTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bigTitleLabel.setForeground(new java.awt.Color(0, 51, 153));
        bigTitleLabel.setText("PayWeb3");
        getContentPane().add(bigTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 20));

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        titleLabel.setForeground(new java.awt.Color(0, 51, 153));
        titleLabel.setText("Query");
        getContentPane().add(titleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 30));

        payGateIDField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        payGateIDField.setForeground(new java.awt.Color(0, 0, 153));
        payGateIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payGateIDFieldActionPerformed(evt);
            }
        });
        payGateIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                payGateIDFieldKeyTyped(evt);
            }
        });
        getContentPane().add(payGateIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, 25));

        referenceField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        referenceField.setForeground(new java.awt.Color(0, 0, 153));
        referenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                referenceFieldActionPerformed(evt);
            }
        });
        referenceField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                referenceFieldKeyTyped(evt);
            }
        });
        getContentPane().add(referenceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 220, 25));

        sendButton.setBackground(new java.awt.Color(0, 0, 204));
        sendButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sendButton.setForeground(new java.awt.Color(255, 255, 255));
        sendButton.setText("Send");
        sendButton.setToolTipText("Sample");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 220, 40));

        requestArea.setColumns(20);
        requestArea.setRows(5);
        requestArea.setToolTipText("[750, 510]");
        requestArea.setName("Test"); // NOI18N
        jScrollPane1.setViewportView(requestArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 860, 220));

        responseArea.setColumns(20);
        responseArea.setRows(5);
        jScrollPane2.setViewportView(responseArea);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 860, 230));

        defaultButton.setBackground(new java.awt.Color(0, 0, 255));
        defaultButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        defaultButton.setForeground(new java.awt.Color(255, 255, 255));
        defaultButton.setText("Default");
        defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtonActionPerformed(evt);
            }
        });
        getContentPane().add(defaultButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 220, 40));

        REFERENCE.setText("Reference");
        getContentPane().add(REFERENCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        checksumField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checksumField.setForeground(new java.awt.Color(0, 0, 153));
        checksumField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checksumFieldActionPerformed(evt);
            }
        });
        checksumField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                checksumFieldKeyTyped(evt);
            }
        });
        getContentPane().add(checksumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 220, 25));

        jLabel6.setText("Checksum");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        payRequestIDField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        payRequestIDField.setForeground(new java.awt.Color(0, 0, 153));
        payRequestIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payRequestIDFieldActionPerformed(evt);
            }
        });
        payRequestIDField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                payRequestIDFieldKeyTyped(evt);
            }
        });
        getContentPane().add(payRequestIDField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 220, 25));

        jLabel13.setText("PAY REQUEST ID");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel15.setText("Pay Gate ID");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void referenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_referenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_referenceFieldActionPerformed

    private void payGateIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payGateIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payGateIDFieldActionPerformed

    private void payGateIDFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payGateIDFieldKeyTyped
        display();
    }//GEN-LAST:event_payGateIDFieldKeyTyped

    private void referenceFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_referenceFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_referenceFieldKeyTyped

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_defaultButtonActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        try {
            MyObject object = new MyObject();
            object.setProperty("PAYGATE_ID", payGateIDField.getText());
            object.setProperty("REFERENCE", referenceField.getText());
            object.setProperty("CHECKSUM", checksumField.getText());
            object.setProperty("PAY_REQUEST_ID", payRequestIDField.getText());
            PayWeb pw = new PayWeb("https://secure.paygate.co.za/payweb3/query.trans");
            String response = pw.request(pw.body(object));
            responseArea.setText(response);
        } catch (IOException ex) {
            Logger.getLogger(Query.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void checksumFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_checksumFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_checksumFieldKeyTyped

    private void checksumFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checksumFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checksumFieldActionPerformed

    private void payRequestIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_payRequestIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_payRequestIDFieldActionPerformed

    private void payRequestIDFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_payRequestIDFieldKeyTyped
        // TODO add your handling code here:
        display();
    }//GEN-LAST:event_payRequestIDFieldKeyTyped

    /**
     * display params in text area
     */
    private void display() {
        // TODO add your handling code here:
        PayWeb pw = new PayWeb();
        MyObject object = new MyObject();
        object.setProperty("PAYGATE_ID", payGateIDField.getText());
        object.setProperty("REFERENCE", referenceField.getText());
        object.setProperty("PAY_REQUEST_ID", payRequestIDField.getText());
        object.setProperty("CHECKSUM", checksumField.getText());
        String body = pw.bodyDisplay(object);
        requestArea.setText(body);
    }

    /**
     * default params in text area
     */
    private void reset() {
        // TODO add your handling code here:
        MyObject m = new Mockups().paywebQuery();
        String body = new PayWeb().bodyDisplay(m);
        payGateIDField.setText((String) m.getProperty("PAYGATE_ID"));
        referenceField.setText((String) m.getProperty("REFERENCE"));
        payRequestIDField.setText((String) m.getProperty("PAY_REQUEST_ID"));
        checksumField.setText((String) m.getProperty("CHECKSUM"));
        requestArea.setText(body);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Query.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Query().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel REFERENCE;
    private javax.swing.JLabel bigTitleLabel;
    private javax.swing.JTextField checksumField;
    private javax.swing.JButton defaultButton;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField payGateIDField;
    private javax.swing.JTextField payRequestIDField;
    private javax.swing.JTextField referenceField;
    private javax.swing.JTextArea requestArea;
    private javax.swing.JTextArea responseArea;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables
}
